Portfolio Project Milestone 2
Santosh-Konappanavar/PortFolio pull request #2
Opened 2023-01-14 17:57 UTC by Santosh-Konappanavar

Portfolio Project Milestone 2
The following features have been added to the portfolio website.

The Portfolio website now has the details of each project.
The about me page was added to provide a brief description of my experience
The languages, frameworks and skills have also been added

2023-01-14 18:54 UTC, MeqdamAlqudah requested changes
Hi @Santosh-Konappanavar  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/74744787/212491401-570240c1-7eb1-4cb9-b9ae-428ba51cb901.png)


 ## Highlights
:+1: Readme file
:+1: no Linter errors
:+1:  you got most of the project from the first time

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 18:54 UTC, MeqdamAlqudah commented on index.html
> +    <section class ="worksection">
- [ ] Please make sure that the mrgin between the paragraph and the tech list matches the design 
your code 
![image](https://user-images.githubusercontent.com/74744787/212490832-dec6eb56-09b7-421d-a2e7-d55d77f81425.png)
Figma 
![image](https://user-images.githubusercontent.com/74744787/212490850-d0c14dfe-b75e-4800-9471-e02e8260b03b.png)

- [ ] Please fix the margin between the work section and the about me section
![image](https://user-images.githubusercontent.com/74744787/212490936-9ffccb4c-66ac-4ada-a98e-47f8bec66ae0.png)
the design 
![image](https://user-images.githubusercontent.com/74744787/212490952-194b0bbf-cbce-4b77-be84-e00bd3451d52.png)

2023-01-14 18:54 UTC, MeqdamAlqudah commented on index.html
> +        </div>
- [ ] Please fix the margin between the about me paragraph and the button here 
![image](https://user-images.githubusercontent.com/74744787/212491071-975ab4e8-db4d-4f2e-bd6e-ede369ef9d79.png)

2023-01-14 18:54 UTC, MeqdamAlqudah commented on index.html
> +
- [ ] Please make sure that the font family matches the design 
![image](https://user-images.githubusercontent.com/74744787/212491296-5cb7fbcd-cd87-420c-8b7e-3865ef183be0.png)
Figma design 
![image](https://user-images.githubusercontent.com/74744787/212491317-54c3c8be-ee95-410c-bfd9-8f3808ded270.png)

2023-01-17 04:21 UTC, Shedrack-Sunday approved these changes
Hi @Santosh-Konappanavar  👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
 - Great design 👏 
 -  Descriptive Pull Request(PR) ✅ 
- Proper use of Github features
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 

 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 04:22 UTC, merged